services:
    _defaults:
        autowire: true
        autoconfigure: true
        
    App\Infrastructure\Ui\Controllers\:
        resource: '../src/Infrastructure/Ui/Controllers/'
        tags: ['controller.service_arguments']
