<?php

namespace ContainerL7IcTvM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAbstractControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Infrastructure\Ui\Controllers\AbstractController' shared autowired service.
     *
     * @return \App\Infrastructure\Ui\Controllers\AbstractController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Infrastructure'.\DIRECTORY_SEPARATOR.'Ui'.\DIRECTORY_SEPARATOR.'Controllers'.\DIRECTORY_SEPARATOR.'AbstractController.php';

        return $container->services['App\\Infrastructure\\Ui\\Controllers\\AbstractController'] = new \App\Infrastructure\Ui\Controllers\AbstractController();
    }
}
