<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJRUpGEA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJRUpGEA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJRUpGEA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJRUpGEA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJRUpGEA\App_KernelDevDebugContainer([
    'container.build_hash' => 'JRUpGEA',
    'container.build_id' => '149183ea',
    'container.build_time' => 1601813696,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJRUpGEA');
