<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXkhiYVm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXkhiYVm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXkhiYVm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXkhiYVm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXkhiYVm\App_KernelDevDebugContainer([
    'container.build_hash' => 'XkhiYVm',
    'container.build_id' => 'e8c07eff',
    'container.build_time' => 1601898848,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXkhiYVm');
