<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUoxxo5g\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUoxxo5g/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUoxxo5g.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUoxxo5g\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUoxxo5g\App_KernelDevDebugContainer([
    'container.build_hash' => 'Uoxxo5g',
    'container.build_id' => 'c1e70d40',
    'container.build_time' => 1602145526,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUoxxo5g');
