<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUwcZg14\App_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUwcZg14/App_KernelDevContainer.php') {
    touch(__DIR__.'/ContainerUwcZg14.legacy');

    return;
}

if (!\class_exists(App_KernelDevContainer::class, false)) {
    \class_alias(\ContainerUwcZg14\App_KernelDevContainer::class, App_KernelDevContainer::class, false);
}

return new \ContainerUwcZg14\App_KernelDevContainer([
    'container.build_hash' => 'UwcZg14',
    'container.build_id' => '5a37bb03',
    'container.build_time' => 1601481728,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUwcZg14');
